package com.tiny.mapper;

import com.tiny.entity.WechatUser;
import com.tiny.entity.WechatUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WechatUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    long countByExample(WechatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    int deleteByExample(WechatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    int insert(WechatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    int insertSelective(WechatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    List<WechatUser> selectByExample(WechatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    WechatUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WechatUser record, @Param("example") WechatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WechatUser record, @Param("example") WechatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WechatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WechatUser record);
}