package com.tiny.entity;

import java.util.Date;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.prize
     *
     * @mbg.generated
     */
    private Double prize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.prize_type
     *
     * @mbg.generated
     */
    private Byte prizeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_type
     *
     * @mbg.generated
     */
    private Integer goodsType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.top_sort_time
     *
     * @mbg.generated
     */
    private Date topSortTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.top_sort_status
     *
     * @mbg.generated
     */
    private Byte topSortStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.img_url
     *
     * @mbg.generated
     */
    private String imgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_status
     *
     * @mbg.generated
     */
    private Byte goodsStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_remark
     *
     * @mbg.generated
     */
    private String goodsRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.sell_limit_start_time
     *
     * @mbg.generated
     */
    private Date sellLimitStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.sell_limit_end_time
     *
     * @mbg.generated
     */
    private Date sellLimitEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.operator_id
     *
     * @mbg.generated
     */
    private Integer operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.sell_status
     *
     * @mbg.generated
     */
    private Byte sellStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.name
     *
     * @return the value of goods.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.name
     *
     * @param name the value for goods.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.prize
     *
     * @return the value of goods.prize
     *
     * @mbg.generated
     */
    public Double getPrize() {
        return prize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.prize
     *
     * @param prize the value for goods.prize
     *
     * @mbg.generated
     */
    public void setPrize(Double prize) {
        this.prize = prize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.prize_type
     *
     * @return the value of goods.prize_type
     *
     * @mbg.generated
     */
    public Byte getPrizeType() {
        return prizeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.prize_type
     *
     * @param prizeType the value for goods.prize_type
     *
     * @mbg.generated
     */
    public void setPrizeType(Byte prizeType) {
        this.prizeType = prizeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_type
     *
     * @return the value of goods.goods_type
     *
     * @mbg.generated
     */
    public Integer getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_type
     *
     * @param goodsType the value for goods.goods_type
     *
     * @mbg.generated
     */
    public void setGoodsType(Integer goodsType) {
        this.goodsType = goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.top_sort_time
     *
     * @return the value of goods.top_sort_time
     *
     * @mbg.generated
     */
    public Date getTopSortTime() {
        return topSortTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.top_sort_time
     *
     * @param topSortTime the value for goods.top_sort_time
     *
     * @mbg.generated
     */
    public void setTopSortTime(Date topSortTime) {
        this.topSortTime = topSortTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.top_sort_status
     *
     * @return the value of goods.top_sort_status
     *
     * @mbg.generated
     */
    public Byte getTopSortStatus() {
        return topSortStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.top_sort_status
     *
     * @param topSortStatus the value for goods.top_sort_status
     *
     * @mbg.generated
     */
    public void setTopSortStatus(Byte topSortStatus) {
        this.topSortStatus = topSortStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.img_url
     *
     * @return the value of goods.img_url
     *
     * @mbg.generated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.img_url
     *
     * @param imgUrl the value for goods.img_url
     *
     * @mbg.generated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.description
     *
     * @return the value of goods.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.description
     *
     * @param description the value for goods.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_status
     *
     * @return the value of goods.goods_status
     *
     * @mbg.generated
     */
    public Byte getGoodsStatus() {
        return goodsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_status
     *
     * @param goodsStatus the value for goods.goods_status
     *
     * @mbg.generated
     */
    public void setGoodsStatus(Byte goodsStatus) {
        this.goodsStatus = goodsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_remark
     *
     * @return the value of goods.goods_remark
     *
     * @mbg.generated
     */
    public String getGoodsRemark() {
        return goodsRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_remark
     *
     * @param goodsRemark the value for goods.goods_remark
     *
     * @mbg.generated
     */
    public void setGoodsRemark(String goodsRemark) {
        this.goodsRemark = goodsRemark == null ? null : goodsRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.sell_limit_start_time
     *
     * @return the value of goods.sell_limit_start_time
     *
     * @mbg.generated
     */
    public Date getSellLimitStartTime() {
        return sellLimitStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.sell_limit_start_time
     *
     * @param sellLimitStartTime the value for goods.sell_limit_start_time
     *
     * @mbg.generated
     */
    public void setSellLimitStartTime(Date sellLimitStartTime) {
        this.sellLimitStartTime = sellLimitStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.sell_limit_end_time
     *
     * @return the value of goods.sell_limit_end_time
     *
     * @mbg.generated
     */
    public Date getSellLimitEndTime() {
        return sellLimitEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.sell_limit_end_time
     *
     * @param sellLimitEndTime the value for goods.sell_limit_end_time
     *
     * @mbg.generated
     */
    public void setSellLimitEndTime(Date sellLimitEndTime) {
        this.sellLimitEndTime = sellLimitEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.create_time
     *
     * @return the value of goods.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.create_time
     *
     * @param createTime the value for goods.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.update_time
     *
     * @return the value of goods.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.update_time
     *
     * @param updateTime the value for goods.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.operator_id
     *
     * @return the value of goods.operator_id
     *
     * @mbg.generated
     */
    public Integer getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.operator_id
     *
     * @param operatorId the value for goods.operator_id
     *
     * @mbg.generated
     */
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.sell_status
     *
     * @return the value of goods.sell_status
     *
     * @mbg.generated
     */
    public Byte getSellStatus() {
        return sellStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.sell_status
     *
     * @param sellStatus the value for goods.sell_status
     *
     * @mbg.generated
     */
    public void setSellStatus(Byte sellStatus) {
        this.sellStatus = sellStatus;
    }
}